### ISSUE TITLE
Annotation system tests

### ISSUE THREAD

**Issue by ChasNelson1990** [gliff-ai/annotate#410]
## Describe the test

We need a series of system tests and visual tests, using BrowserStack Automate, Selenium and Percy Snapshot (@joshuajames-smith), for each annotation type:

- [x] paintbrush
- [x] eraser
- [x] fill  (covered by unittest #407)
- [x] normal spline
- [x] lasso spline
- [x] close active spline (covered by unittest #407)
- [x] convert spline to paintbrush (covered by unittest #407)
- [x] bounding box

*NOTE: I recommend splitting this issue into one for each annotation for easier tracking of progress but will leave this to @philipjackson ***
